### ISSUE TITLE
Command raised an exception

### ISSUE THREAD

**Issue by SiirRandall** [AnthonyBloomer/weather-api#12]
Hello, I have to say I love this API. It runs fine when it is in a main program. But when I use a class and use your API I got. 

```Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'unit'```

I am using this for my discord bot to give weather data.  

This is the code I am using 
```python
import discord
from discord.ext import commands
from weather import Weather, Unit


def setup(bot):
    bot.add_cog(Weather(bot))

class Weather:
    """Weather Cog"""
     
    def __init__(self, bot):
        self.bot = bot
    
    @commands.command()
    async def weathertexttest(self, ctx, TempUnit, *city: str):
        """Displays the weather from location provided in text form. You can use F or C for temprateure. Example !weather f death valley"""
        if TempUnit.lower() == "c":
            weather = Weather(unit=Unit.CELSIUS)
            unit = "C"
        elif TempUnit.lower() == "f":
            weather = Weather(unit=Unit.FAHRENHEIT)
            unit = "F"
        else: await ctx.send("Please use F or C for tempreature unit. Example !weather f las vegas")
        lookup = weather.lookup_by_location("{}".format(' '.join(city)))
        condition = lookup.condition
        forecast = lookup.forecast[0]
        await ctx.send("Today in " + lookup.location.city + lookup.location.region + " " + lookup.location.country + " it will be " + condition.text  + " with a high of " + forecast.high + "°" + unit + " with a low of " + forecast.low + "°" + unit + " current temp is " + condition.temp + "°" + unit)
```

**Comment by AnthonyBloomer** [comment]
Hi @SiirRandall, I think since you have a class called Weather and are importing the Weather class from my lib, it's causing a mismatch. I'd suggest renaming your Weather class or import Weather as a different name: i.e `from weather import Weather as WeatherApi`. Let me if that solves your problem.

**Comment by SiirRandall** [comment]
That is exactly what it was. I am so sorry to bother you with a stupid typo question like that. Thank you again for your help. Also, thank you for being really level headed about it. Keep up the awesome work.
