### ISSUE TITLE
Weather lookup returns None

### ISSUE THREAD

**Issue by AwesomeIndustry** [AnthonyBloomer/weather-api#14]
Hi,
When I try to use the `lookup_by_location()` function, it returns None. Here is my code (Python 2.7.13):
```
import weather
weatherobj = weather.Weather(unit='f')
print(weatherobj.lookup_by_location('dublin'))
#Prints None
```
When I tried installing version 1.0.3 (using pip), I got this error:
```
INFO:weather.weather:Status Code: 200
INFO:weather.weather:{u'query': {u'count': 0, u'lang': u'en-US', u'results': None, u'created': u'2018-08-30T20:06:21Z'}}
WARNING:weather.weather:No results found: {u'query': {u'count': 0, u'lang': u'en-US', u'results': None, u'created': u'2018-08-30T20:06:21Z'}} 
None
```

**Comment by AwesomeIndustry** [comment]
Hmm... it looks like this might be a problem with Yahoo's API:
https://developer.yahoo.com/weather/

**Comment by AnthonyBloomer** [comment]
Hey @AwesomeIndustry. I just checked and the problem with Yahoo's API is resolved now. 👍
