### ISSUE TITLE
Latitude and Longitude

### ISSUE THREAD

**Issue by kuzeyron** [AnthonyBloomer/weather-api#2]
Hi! I'm trying to test your API.
But I'm having problems with giving the latitude and longitude so it can return the weather data.

Any ideas how to work this out?

Regards, Mathias

**Comment by AnthonyBloomer** [comment]
Hi Mathias,

You just need to pass the lat, lng coordinates into the lookup function as follows:

```
w = weather.lookup_by_location("(53.3494,-6.2601)")
```

This is the query I used in the Yahoo console:

```
select * from weather.forecast where woeid in (SELECT woeid FROM geo.places WHERE text="(53.3494,-6.2601)")
```

Let me know if that solves your problem.

**Comment by kuzeyron** [comment]
Thank you!
