### ISSUE TITLE
Can't lookup by location

### ISSUE THREAD

**Issue by dendory** [AnthonyBloomer/weather-api#3]
I'm not quite sure why but your example isn't working for me:

	$ python3
	Python 3.4.5 (default, Dec 11 2017, 14:22:24)
	[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux
	Type "help", "copyright", "credits" or "license" for more information.
	>>> from weather import Weather
	>>> weather = Weather
	>>> location = weather.lookup_by_location('dublin')
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	TypeError: lookup_by_location() missing 1 required positional argument: 'location'
	>>> location = weather.lookup_by_location(weather, 'dublin')
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/usr/lib/python3.4/site-packages/weather/weather.py", line 16, in lookup_by_location
	    results = self._call(url)
	TypeError: _call() missing 1 required positional argument: 'url'
	>>>

Install log:

	$ sudo pip3 install python3-weather-api
	Collecting python3-weather-api
	  Downloading python3-weather-api-0.0.3c.tar.gz
	Requirement already satisfied: requests in /usr/lib/python3.4/site-packages (from python3-weather-api)
	Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.4/site-packages (from requests->python3-weather-api)
	Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python3.4/site-packages (from requests->python3-weather-api)
	Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python3.4/site-packages (from requests->python3-weather-api)
	Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.4/site-packages (from requests->python3-weather-api)
	Building wheels for collected packages: python3-weather-api
	  Running setup.py bdist_wheel for python3-weather-api ... done
	  Stored in directory: /root/.cache/pip/wheels/11/68/ae/88c076a70f33b1dd00491dd391534729a7d9718dc8fdd870c0
	Successfully built python3-weather-api
	Installing collected packages: python3-weather-api
	Successfully installed python3-weather-api-0.0.3rc0

**Comment by AnthonyBloomer** [comment]
Hi @dendory 

It should be 

```
weather = Weather()
location = weather.lookup_by_location('dublin')
```

Let me know if that solves your problem.
