### ISSUE TITLE
location function issue

### ISSUE THREAD

**Issue by ahmednabil950** [AnthonyBloomer/weather-api#5]
In the previous versions it was working, now it raises exception with None result

```
location = weather.lookup_by_location('dublin')
condition = location.condition()
```

> Showers
> {'query': {'count': 0,
>            'created': '2018-03-14T18:30:00Z',
>            'lang': 'en-US',
>            'results': None}}
> AttributeError: 'NoneType' object has no attribute 'condition'

**Comment by AnthonyBloomer** [comment]
Hi Ahmed,

I'm not able to replicate this issue. Are you running the latest version '0.0.6'? What location are you looking up?

Calling `location.condition()` returns a Condition object which contains the following methods:

``` python
def date(self):
    return self._condition_data['date']

def text(self):
    return self._condition_data['text']

def code(self):
    return self._condition_data['code']

def temp(self):
    return self._condition_data['temp']
```

So if you wanted to get the condition text, you'd run:

``` python
location = weather.lookup_by_location('dublin')
condition = location.condition()
print(condition().text()) # Partly Cloudy
```

Let me know if this solves the issue.

**Comment by ahmednabil950** [comment]
Hi Anthony,

I do not know why the error disappeared when i tried it yesterday. I did
not change any thing in the old code.
May be it was some issue related to yahoo infrastructure.
I am glad it worked again and thanks for your consideration.

**Comment by AnthonyBloomer** [comment]
That's great Ahmed.
