### ISSUE TITLE
Forecast data

### ISSUE THREAD

**Issue by klumpelstiltskin** [AnthonyBloomer/weather-api#7]
Would you be able to add the remaining two data fields in forecast data? Specifically 'code' as it relates to a project I'm working on. Thanks!

**Comment by AnthonyBloomer** [comment]
Hi, thanks for raising this issue, it's something I've been meaning to do for a while. I updated the Forecast object with its missing attributes and also added Unit and Wind obj.

**Comment by klumpelstiltskin** [comment]
Works like a charm, thanks!
