### ISSUE TITLE
Generating forecast data

### ISSUE THREAD

**Issue by mitchellkrogza** [AnthonyBloomer/weather-api#8]
First off @AnthonyBloomer this is a really great and simple project best one I have found yet. 
I'm very new to python and am not quite figuring out the example for getting the forecast data for 3/5/7 days.

Is there no way to pass a command line argument yet for this? 
Something like `weather johannesburg --u c -f 7`

Otherwise could you possibly guide this Python NOOB on how to implement that forecast example?

**Comment by mitchellkrogza** [comment]
Hi @AnthonyBloomer many thanks for the prompt reply. 
I actually want to get a 3 day forecast, as in all 3 of the next 3 days, or 5 or 7.

So current output using the basic command line now gives me
```
$weather johannesburg --u c
Weather report for Johannesburg, South Africa
Condition: Mostly Cloudy 
Temperature: 20
```
But I'm looking to extend it to something like this

```
Weather report for Johannesburg, South Africa
Condition: Mostly Cloudy 
Temperature: 20
Day1: Conditions
Day2: Conditions
Day3: Conditions 
``

**Comment by AnthonyBloomer** [comment]
Ah I get you now. So if we wanted to get a specific range we could add a start and end argument then print each forecast within that specific range. For example:

``` python
pa.add_argument("--f"', "--forecast", nargs="?", "Pass this argument to get a weather forecast")
pa.add_argument("--s"', "--start", nargs="?", "The forecast start")
pa.add_argument("--e"', "--end", nargs="?", "The forecast end")

if args.forecast:
   start = 0 if not args.start else args.start # If the start argument isn't set, set the start as the first element in the forecast array.
   end =  len(location.forecast) if not args.end else args.end # if the end argument isn't set, set the end as the last element in the forecast array.
   for forecast in location.forecast[start:end]:
       print("Day%s: %s" % (start, forecast.text))
       start += 1
```

Does that help? Something like that could work.

**Comment by mitchellkrogza** [comment]
That would be awesome

**Comment by mitchellkrogza** [comment]
I'll test this out in the morning and once my Python skills improve I hope to contribute any features I add as PR's.

**Comment by AnthonyBloomer** [comment]
Hi @mitchellkrogza, that looks really good so far. Good work. 

The weather api doesn't indicate when they update their API. I'd assume it'd be at least once a day.

**Comment by AnthonyBloomer** [comment]
Any update on this @mitchellkrogza?

**Comment by mitchellkrogza** [comment]
Hita @AnthonyBloomer I kinda gave up due to my limited Python skills but will still look into this in the future. I found an API from openweather which produces pretty simple html files which I pull every 10 minutes and format them to fit my site and my amount of API calls is below their limit before moving to paid so for now I have a solution but still need to look into your better at a later date as I can pull much more info and longer term forecasts.

**Comment by AnthonyBloomer** [comment]
That's cool @mitchellkrogza. I'll leave this issue open for now anyway :)

**Comment by AnthonyBloomer** [comment]
Added some of the ideas from this thread with https://github.com/AnthonyBloomer/weather-api/commit/65a706257630df2943bc159b6cfaffd5304c27b0
